input_data:
  participant_id_col: "ParticipantID"
  result_col: "Value"
  uncertainty_col: "Uncertainty"

calculation:
  method: "CRM"
  sigma_pt: 0.15
  crm:
    certified_value: 10.0
    uncertainty: 0.05

reporting:
  default_format: "pdf"
  plots:
    generate_histogram: true
    histogram_bins: 20