input_data:
  participant_id_col: "ParticipantID"
  result_col: "Value"
  uncertainty_col: "Uncertainty"

calculation:
  method: "AlgorithmA"
  sigma_pt: 0.15
  algorithm_a:
    tolerance: 1.0e-5
    max_iterations: 50

reporting:
  default_format: "pdf"
  plots:
    generate_histogram: true
    histogram_bins: 20